# output paths for hydra logs
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - override launcher: joblib

run:
  dir: logs/runs/${exp_name}
sweep:
  dir: logs/multiruns/
  subdir: ${exp_name}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"
  chdir: True
