# @package _global_
defaults:
    - override /callbacks: ar_models
model:
    _target_: src.models.tar.TAR
    lr: 1e-3
    b1: 0.9
    b2: 0.999
    d_model: 256
    nhead: 4
    num_layers: 4
    class_cond: false
    n_classes: ${datamodule.n_classes}